# Imports

In [1]:
from sklearn import svm
import numpy as np
import matplotlib.pyplot as plt

# Information on Support vector machines
[sklearn website](https://scikit-learn.org/stable/modules/svm.html#svm-kernels)

# Create some fake data

In [2]:
X = np.random.rand(20)
print(X)

[0.00308122 0.25865966 0.83600584 0.34755135 0.46534994 0.6492493
 0.16142487 0.52242716 0.66373048 0.0580653  0.65593346 0.84373899
 0.1540254  0.77479057 0.40662182 0.13985343 0.54261936 0.5815225
 0.57731462 0.74569474]


In [3]:
## reshape data for fitting model
X = X.reshape(-1,1)
print(X)

[[0.00308122]
 [0.25865966]
 [0.83600584]
 [0.34755135]
 [0.46534994]
 [0.6492493 ]
 [0.16142487]
 [0.52242716]
 [0.66373048]
 [0.0580653 ]
 [0.65593346]
 [0.84373899]
 [0.1540254 ]
 [0.77479057]
 [0.40662182]
 [0.13985343]
 [0.54261936]
 [0.5815225 ]
 [0.57731462]
 [0.74569474]]


In [4]:
y = np.random.randint(0,2, size=20)
print(y)

[0 1 1 0 0 0 1 1 1 1 0 1 0 1 0 1 0 1 1 0]


# Call our SVM module to create an instance of a classifier

In [5]:
clf = svm.SVC()

## Explore the inputs of the SVC

In [6]:
svm.SVC??

Init signature:
svm.SVC(
    *,
    C=1.0,
    kernel='rbf',
    degree=3,
    gamma='scale',
    coef0=0.0,
    shrinking=True,
    probability=False,
    tol=0.001,
    cache_size=200,
    class_weight=None,
    verbose=False,
    max_iter=-1,
    decision_function_shape='ovr',
    break_ties=False,
    random_state=None,
)
Source:        
class SVC(BaseSVC):
    """C-Support Vector Classification.

    The implementation is based on libsvm. The fit time scales at least
    quadratically with the number of samples and may be impractical
    beyond tens of thousands of samples. For large datasets
    consider using :class:`~sklearn.svm.LinearSVC` or
    :class:`~sklearn.linear_model.SGDClassifier` instead, possibly after a
    :class:`~sklearn.kernel_approximation.Nystroem` transformer.

    The multiclass support is handled according to a one-vs-one scheme.

    For details on the precise mathematical formulation of the provided
    kernel functions and how `gamma`, `coef0` and `degr

# Fit model

In [11]:
# Fit the model to x and y
clf.fit(X,y)

SVC()

In [12]:
# Verify we only have two classes
clf.classes_

array([0, 1])

## See how well the training data fits

In [13]:
# Get the training classification score
clf.score(X,y)

0.6

# What if we change the kernel?

In [14]:
# Kernels accepted by the function
list_kerns = ['linear', 'poly', 'rbf', 'sigmoid']

# Loop over them and train a model

for kernel in list_kerns:
    print(f'Kernel being used is {kernel}')
    clf = svm.SVC(kernel=kernel)
    clf.fit(X,y)
    print(clf.score(X,y))

Kernel being used is linear
0.55
Kernel being used is poly
0.55
Kernel being used is rbf
0.6
Kernel being used is sigmoid
0.55
