In [25]:
import pandas as pd
import numpy as np
import seaborn as sns


# Import data

In [26]:
brain_data = pd.read_csv('./data/eig_centrality.csv', header=None)
brain_data.head()

0         1         2    3    4    5         6         7    8    9    ...  \
0    1 -0.067894 -0.062832    0    0    0 -0.031240 -0.071004    0    0  ...   
1    1  0.031793  0.025996    0    0    0  0.122030  0.109220    0    0  ...   
2    1 -0.005251 -0.015806    0    0    0 -0.124040 -0.117020    0    0  ...   
3    1  0.123150  0.096576    0    0    0 -0.045236 -0.005143    0    0  ...   
4    1 -0.059846 -0.024500    0    0    0 -0.022105  0.022153    0    0  ...   

        285       286           287           288       289       290  \
0 -0.112760 -0.106070  0.000000e+00  0.000000e+00 -0.028195 -0.024616   
1  0.078364  0.049836  0.000000e+00  6.938900e-18 -0.076947 -0.078418   
2  0.021125  0.014470  0.000000e+00 -1.734700e-18  0.068705  0.084321   
3 -0.043127 -0.024063  5.551100e-17 -1.110200e-16 -0.064510 -0.100380   
4 -0.026404 -0.004397 -4.336800e-19  0.000000e+00 -0.068379  0.006091   

        291       292       293       294  
0 -0.042535 -0.087451  0.003145 -0.047196  
1 -0.064815  0.095082  0.054585  0.076347  
2  0.047107  0.004649 -0.142760 -0.129450  
3 -0.112950 -0.099919 -0.006036 -0.004228  
4 -0.050172  0.056009  0.077894  0.016500  

[5 rows x 295 columns]

# Data preprocessing

In [27]:
# Optional: drop zero columns
brain_data = brain_data.loc[:, (brain_data != 0).any(axis=0)]
brain_data.head()

0         1         2         6         7         10        12        13   \
0    1 -0.067894 -0.062832 -0.031240 -0.071004 -0.030888  0.009534  0.044660   
1    1  0.031793  0.025996  0.122030  0.109220 -0.005733  0.017223 -0.072822   
2    1 -0.005251 -0.015806 -0.124040 -0.117020 -0.017355 -0.035984  0.106950   
3    1  0.123150  0.096576 -0.045236 -0.005143 -0.017959 -0.060064  0.008232   
4    1 -0.059846 -0.024500 -0.022105  0.022153  0.079495 -0.013115  0.019867   

        14        15   ...       285       286           287           288  \
0  0.043163  0.025440  ... -0.112760 -0.106070  0.000000e+00  0.000000e+00   
1 -0.077072 -0.126650  ...  0.078364  0.049836  0.000000e+00  6.938900e-18   
2  0.011851  0.077032  ...  0.021125  0.014470  0.000000e+00 -1.734700e-18   
3 -0.076910 -0.042061  ... -0.043127 -0.024063  5.551100e-17 -1.110200e-16   
4  0.032033  0.012232  ... -0.026404 -0.004397 -4.336800e-19  0.000000e+00   

        289       290       291       292       293       294  
0 -0.028195 -0.024616 -0.042535 -0.087451  0.003145 -0.047196  
1 -0.076947 -0.078418 -0.064815  0.095082  0.054585  0.076347  
2  0.068705  0.084321  0.047107  0.004649 -0.142760 -0.129450  
3 -0.064510 -0.100380 -0.112950 -0.099919 -0.006036 -0.004228  
4 -0.068379  0.006091 -0.050172  0.056009  0.077894  0.016500  

[5 rows x 274 columns]

# PCA

This might not be the best approach because we have the one hot encoded categorical variable (binary classification)

By applying PCA, we lose some of the variance (i.e., information). By reducing the dimensionality of the data, PCA will reduce the size of the data.
 - This will improve the performance of machine learning algorithms.
 - This will reduce hardware requirements and speed up the training process.
 - This will allow us to easily understand the underlying structure of the data.
 - This will allow us to visualize the data on a 2d or 3d plot (if we choose the number of principal components as 2 or 3).

## Exploratory work

In [28]:
# Get feature matrix
X = abs(brain_data.iloc[:,1:].values)
y = brain_data.iloc[:,0].values
print(X)
print(y)

[[6.7894e-02 6.2832e-02 3.1240e-02 ... 8.7451e-02 3.1445e-03 4.7196e-02]
 [3.1793e-02 2.5996e-02 1.2203e-01 ... 9.5082e-02 5.4585e-02 7.6347e-02]
 [5.2506e-03 1.5806e-02 1.2404e-01 ... 4.6495e-03 1.4276e-01 1.2945e-01]
 ...
 [2.6920e-03 1.4674e-02 1.0568e-01 ... 3.7322e-02 8.6381e-02 9.1878e-02]
 [6.3993e-02 2.5404e-02 4.5130e-02 ... 6.4920e-05 5.0832e-03 1.0966e-02]
 [2.8025e-03 6.5748e-02 1.1062e-01 ... 1.5098e-02 1.2126e-01 8.5409e-02]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [29]:
# Optional: Standardize the features
from sklearn.preprocessing import StandardScaler

## Create object
scaler = StandardScaler()
## Calculate mean and std
scaler.fit(X)
## Transform the values
X_scaled = scaler.transform(X)

In [30]:
X_scaled

array([[ 0.33139785,  0.39702335, -0.77357546, ...,  1.63585243,
        -1.3571693 , -0.08090501],
       [-0.62764009, -0.66035769,  1.67550156, ...,  1.90141282,
         0.07082187,  0.82105796],
       [-1.33274987, -0.95286265,  1.72972168, ..., -1.24565698,
         2.51856483,  2.46412129],
       ...,
       [-1.40072014, -0.98535682,  1.23445729, ..., -0.10864719,
         0.95348062,  1.30160362],
       [ 0.22776617, -0.67735111, -0.39889015, ..., -1.40520132,
        -1.30335088, -1.20189977],
       [-1.39778466,  0.48072742,  1.3677147 , ..., -0.88204701,
         1.92172362,  1.10144588]])

In [31]:
# apply PCA to all dimensions
from sklearn.decomposition import PCA
pca_60 = PCA(n_components=60, random_state=42)
pca_60.fit(X_scaled)
X_pca_60 = pca_60.transform(X_scaled)
print('Variance explained by all 60 principal components = ', sum(pca_60.explained_variance_ratio_ * 100))

Variance explained by all 60 principal components =  99.99999999999999


In [32]:
# The explained_variance_ratio_ attribute of the PCA() class returns
# a one-dimensional numpy array which contains the values of the
# percentage of variance explained by each of the selected components.
pca_60.explained_variance_ratio_ * 100

array([1.05273612e+01, 6.82178775e+00, 5.07210298e+00, 4.52359118e+00,
       3.88560783e+00, 3.62770949e+00, 3.36403746e+00, 3.17513446e+00,
       2.83080865e+00, 2.67879778e+00, 2.58212715e+00, 2.40692874e+00,
       2.25233411e+00, 2.16281659e+00, 2.10075008e+00, 1.98366113e+00,
       1.86508047e+00, 1.77206366e+00, 1.73615729e+00, 1.72134258e+00,
       1.58304185e+00, 1.53373883e+00, 1.45787391e+00, 1.43967924e+00,
       1.38120272e+00, 1.29201104e+00, 1.26163802e+00, 1.19411516e+00,
       1.18666371e+00, 1.15415312e+00, 1.10960569e+00, 1.03863321e+00,
       1.01646877e+00, 9.59399824e-01, 9.41347050e-01, 8.95542428e-01,
       8.82312171e-01, 8.76373491e-01, 8.10738715e-01, 7.84090470e-01,
       7.54449714e-01, 7.31236357e-01, 7.06771597e-01, 6.97113597e-01,
       6.43095440e-01, 6.16745639e-01, 6.09493359e-01, 5.75715872e-01,
       5.54686052e-01, 5.29092474e-01, 5.17675155e-01, 4.77558713e-01,
       4.48582802e-01, 4.35654414e-01, 4.03732853e-01, 3.95316402e-01,
      

In [33]:
# or look at the cumulutive sum as we add more componenets
np.cumsum(pca_60.explained_variance_ratio_ * 100)

array([ 10.52736124,  17.34914899,  22.42125197,  26.94484315,
        30.83045098,  34.45816048,  37.82219794,  40.9973324 ,
        43.82814105,  46.50693883,  49.08906598,  51.49599471,
        53.74832882,  55.91114541,  58.01189549,  59.99555662,
        61.86063709,  63.63270074,  65.36885803,  67.09020062,
        68.67324247,  70.20698129,  71.66485521,  73.10453445,
        74.48573717,  75.77774821,  77.03938623,  78.23350139,
        79.4201651 ,  80.57431822,  81.68392391,  82.72255712,
        83.73902589,  84.69842571,  85.63977276,  86.53531519,
        87.41762736,  88.29400085,  89.10473957,  89.88883004,
        90.64327975,  91.37451611,  92.0812877 ,  92.7784013 ,
        93.42149674,  94.03824238,  94.64773574,  95.22345161,
        95.77813766,  96.30723014,  96.82490529,  97.302464  ,
        97.75104681,  98.18670122,  98.59043407,  98.98575047,
        99.35180196,  99.69530103, 100.        , 100.        ])

In [34]:
'''
It's incorrect to use PCA on the Y variable
'''
# # Leave X and Y in and don't standardize
# X = brain_data.values
# print(X.shape)

# # apply PCA to all dimensions
# pca_60 = PCA(n_components=60, random_state=42)
# pca_60.fit(X)
# X_pca_60 = pca_60.transform(X)
# print('Variance explained by all 60 principal components = ', sum(pca_60.explained_variance_ratio_ * 100))
# print(pca_60.explained_variance_ratio_ * 100)

"\nIt's incorrect to use PCA on the Y variable\n"

In [35]:
'''
Already Done above
'''
# # What if we just use the X and leave out the categorical variable?
# X = brain_data.iloc[:,1:].values
# print(X.shape)
# ## Create object
# scaler = StandardScaler()
# ## Calculate mean and std
# scaler.fit(X)
# ## Transform the values
# X_scaled = scaler.transform(X)

# # apply PCA to all dimensions
# pca_60_justx = PCA(n_components=60, random_state=42)
# pca_60_justx.fit(X_scaled)
# X_pca_60 = pca_60_justx.transform(X_scaled)
# print('Variance explained by all 60 principal components = ', sum(pca_60_justx.explained_variance_ratio_ * 100))
# print(pca_60_justx.explained_variance_ratio_ * 100)

'\nAlready Done above\n'

In [42]:
# What if we just use the X and not scale 
X = abs(brain_data.iloc[:,1:].values)
print(X.shape)
# apply PCA to all dimensions
pca_60_justx = PCA(n_components=50, random_state=42)
pca_60_justx.fit(X)
X_pca_60 = pca_60_justx.transform(X)
print('Variance explained by all 60 principal components = ', sum(pca_60_justx.explained_variance_ratio_ * 100))
print(pca_60_justx.explained_variance_ratio_ * 100)
np.cumsum(pca_60_justx.explained_variance_ratio_ * 100)

(60, 273)
Variance explained by all 60 principal components =  99.99999999999994
[1.19932837e+01 7.42575957e+00 5.14398802e+00 4.57616288e+00
 4.07669235e+00 3.59211023e+00 3.24636824e+00 3.11879270e+00
 2.74535022e+00 2.65737339e+00 2.45131018e+00 2.34809712e+00
 2.26468060e+00 2.14191706e+00 1.97991024e+00 1.88331988e+00
 1.81183305e+00 1.73152014e+00 1.66450988e+00 1.60891658e+00
 1.50266484e+00 1.44966240e+00 1.41063921e+00 1.34654720e+00
 1.33171741e+00 1.28357341e+00 1.21084324e+00 1.15833305e+00
 1.13852216e+00 1.10394652e+00 1.05137440e+00 1.03046040e+00
 9.68541924e-01 9.24278696e-01 8.87430837e-01 8.56010069e-01
 8.35625765e-01 7.92437143e-01 7.88341566e-01 7.50723013e-01
 7.35114007e-01 7.03718215e-01 6.99749304e-01 6.53905725e-01
 6.17250147e-01 5.95718779e-01 5.75110473e-01 5.46992786e-01
 5.21646073e-01 5.12679757e-01 5.07301551e-01 4.58095062e-01
 4.34218851e-01 4.24794155e-01 3.94058935e-01 3.83234834e-01
 3.44433886e-01 3.27413476e-01 2.80994727e-01 3.41676289e-30]


array([ 11.99328367,  19.41904323,  24.56303125,  29.13919413,
        33.21588648,  36.80799671,  40.05436495,  43.17315765,
        45.91850787,  48.57588127,  51.02719145,  53.37528857,
        55.63996917,  57.78188623,  59.76179647,  61.64511635,
        63.4569494 ,  65.18846953,  66.85297942,  68.461896  ,
        69.96456084,  71.41422324,  72.82486245,  74.17140966,
        75.50312707,  76.78670048,  77.99754372,  79.15587676,
        80.29439892,  81.39834545,  82.44971985,  83.48018025,
        84.44872217,  85.37300087,  86.2604317 ,  87.11644177,
        87.95206754,  88.74450468,  89.53284625,  90.28356926,
        91.01868327,  91.72240148,  92.42215079,  93.07605651,
        93.69330666,  94.28902544,  94.86413591,  95.41112869,
        95.93277477,  96.44545452,  96.95275608,  97.41085114,
        97.84506999,  98.26986414,  98.66392308,  99.04715791,
        99.3915918 ,  99.71900527, 100.        , 100.        ])

## Reducing the number of features meaningfully

In [37]:
# Get X values
X = abs(brain_data.iloc[:,1:].values)

pca_95per = PCA(n_components=0.95, random_state=42)
pca_95per.fit(X)
X_pca_95per = pca_95per.transform(X)
print('Number of principal Componenets', len(pca_95per.explained_variance_ratio_))
print(pca_95per.explained_variance_ratio_ * 100)
np.cumsum(pca_95per.explained_variance_ratio_ * 100)

Number of principal Componenets 48
[11.99328367  7.42575957  5.14398802  4.57616288  4.07669235  3.59211023
  3.24636824  3.1187927   2.74535022  2.65737339  2.45131018  2.34809712
  2.2646806   2.14191706  1.97991024  1.88331988  1.81183305  1.73152014
  1.66450988  1.60891658  1.50266484  1.4496624   1.41063921  1.3465472
  1.33171741  1.28357341  1.21084324  1.15833305  1.13852216  1.10394652
  1.0513744   1.0304604   0.96854192  0.9242787   0.88743084  0.85601007
  0.83562577  0.79243714  0.78834157  0.75072301  0.73511401  0.70371822
  0.6997493   0.65390572  0.61725015  0.59571878  0.57511047  0.54699279]


array([11.99328367, 19.41904323, 24.56303125, 29.13919413, 33.21588648,
       36.80799671, 40.05436495, 43.17315765, 45.91850787, 48.57588127,
       51.02719145, 53.37528857, 55.63996917, 57.78188623, 59.76179647,
       61.64511635, 63.4569494 , 65.18846953, 66.85297942, 68.461896  ,
       69.96456084, 71.41422324, 72.82486245, 74.17140966, 75.50312707,
       76.78670048, 77.99754372, 79.15587676, 80.29439892, 81.39834545,
       82.44971985, 83.48018025, 84.44872217, 85.37300087, 86.2604317 ,
       87.11644177, 87.95206754, 88.74450468, 89.53284625, 90.28356926,
       91.01868327, 91.72240148, 92.42215079, 93.07605651, 93.69330666,
       94.28902544, 94.86413591, 95.41112869])

## For Fun: Logistic Regression and SVM


In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn import svm

# Get X and y values
X = abs(brain_data.iloc[:,1:].values)
y = brain_data.iloc[:,0].values
print(X.shape)
print(y.shape)

# Create train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
## Verify
print(X_train.shape)
print(y_train.shape)

# Initialize pca, logistic regression model, and SVM
pca = PCA(n_components=0.99, random_state=42)
lr = LogisticRegression(multi_class='auto', solver='liblinear')
clf = svm.SVC(kernel='rbf')

# Fit and transform data
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)
lr.fit(X_train_pca, y_train)
clf.fit(X_train_pca, y_train)

# Get Results
print('-------------')
print('Logistic Regression')
train_score = lr.score(X_train_pca, y_train)
print(f'Train Accuracy: {train_score}')
test_score = lr.score(X_test_pca, y_test)
print(f'Test Accuracy: {test_score}')
print('-------------')
print('SVM')
train_score = clf.score(X_train_pca, y_train)
print(f'Train Accuracy: {train_score}')
test_score = clf.score(X_test_pca, y_test)
print(f'Test Accuracy: {test_score}')
print('--------------')



(60, 273)
(60,)
(48, 273)
(48,)
-------------
Logistic Regression
Train Accuracy: 0.6458333333333334
Test Accuracy: 0.3333333333333333
-------------
SVM
Train Accuracy: 1.0
Test Accuracy: 0.5
--------------


# Model Testing

In [39]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
import time

# Get X and y values
X = abs(brain_data.iloc[:,1:].values)
y = brain_data.iloc[:,0].values
print(X.shape)
print(y.shape)

# Create train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=2021)
## Verify
print(X_train.shape)
print(y_train.shape)

# Initialize pca, logistic regression model, and SVM
pca = PCA(n_components=0.95, random_state=42)
models = [AdaBoostClassifier(),
         GradientBoostingClassifier(),
         RandomForestClassifier(), 
         DecisionTreeClassifier(),
         svm.SVC(kernel='rbf')]

# Fit and transform data
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

print('#### PCA Performance ####')
for model in models:
    print('-----------------')
    print(f'{model} being used')
    model.fit(X_train_pca, y_train)
    train_score = model.score(X_train_pca, y_train)
    print(f'Train Accuracy: {train_score}')
    test_score = model.score(X_test_pca, y_test)
    print(f'Test Accuracy: {test_score}')
    time.sleep(3)

print('#### Full data Performance ####')
for model in models:
    print('-----------------')
    print(f'{model} being used')
    model.fit(X_train, y_train)
    train_score = model.score(X_train, y_train)
    print(f'Train Accuracy: {train_score}')
    test_score = model.score(X_test, y_test)
    print(f'Test Accuracy: {test_score}')
    time.sleep(3)

(60, 273)
(60,)
(54, 273)
(54,)
#### PCA Performance ####
-----------------
AdaBoostClassifier() being used
Train Accuracy: 1.0
Test Accuracy: 0.5
-----------------
GradientBoostingClassifier() being used
Train Accuracy: 1.0
Test Accuracy: 0.3333333333333333
-----------------
RandomForestClassifier() being used
Train Accuracy: 1.0
Test Accuracy: 0.3333333333333333
-----------------
DecisionTreeClassifier() being used
Train Accuracy: 1.0
Test Accuracy: 0.3333333333333333
-----------------
SVC() being used
Train Accuracy: 1.0
Test Accuracy: 0.5
#### Full data Performance ####
-----------------
AdaBoostClassifier() being used
Train Accuracy: 1.0
Test Accuracy: 0.3333333333333333
-----------------
GradientBoostingClassifier() being used
Train Accuracy: 1.0
Test Accuracy: 0.3333333333333333
-----------------
RandomForestClassifier() being used
Train Accuracy: 1.0
Test Accuracy: 0.5
-----------------
DecisionTreeClassifier() being used
Train Accuracy: 1.0
Test Accuracy: 0.3333333333333333
--

## Cross validation

In [40]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, RandomForestClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import KFold, cross_validate
import time

# Get X and y values
X = abs(brain_data.iloc[:,1:].values)
y = brain_data.iloc[:,0].values
print(X.shape)
print(y.shape)

# Initialize pca, logistic regression model, and SVM
pca = PCA(n_components=0.95, random_state=42)
models = [AdaBoostClassifier(),
         GradientBoostingClassifier(),
         RandomForestClassifier(), 
         DecisionTreeClassifier(),
         ExtraTreesClassifier(),
         svm.SVC(kernel='rbf'),
         SGDClassifier()
         ]

# Fit and transform data
X_pca = pca.fit_transform(X)

# Initialize Folds
k_fold = KFold( n_splits=10,
                shuffle=True,
                random_state= 2021)

print('#### PCA Performance ####')
for model in models:
    print('-----------------')
    print(f'{model} being used')
    results = cross_validate(model, X_pca, y, cv=k_fold, return_train_score=True)
    train_score = results['train_score']
    test_score = results['test_score']
    print(f'train scores: {train_score}')
    print(f'test scores: {test_score}')
    del results
    del model
    time.sleep(2)
print('---------------------------------')
print('#### Full data Performance ####')
for model in models:
    print('-----------------')
    print(f'{model} being used')
    results = cross_validate(model, X, y, cv=k_fold, return_train_score=True)
    train_score = results['train_score']
    test_score = results['test_score']
    print(f'train scores: {train_score}')
    print(f'test scores: {test_score}')
    del results
    del model
    time.sleep(2)

(60, 273)
(60,)
#### PCA Performance ####
-----------------
AdaBoostClassifier() being used
train scores: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
test scores: [0.5        0.         0.5        0.5        0.83333333 0.66666667
 0.66666667 0.33333333 0.66666667 0.66666667]
-----------------
GradientBoostingClassifier() being used
train scores: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
test scores: [0.5        0.5        0.66666667 0.33333333 0.66666667 0.5
 0.33333333 0.5        0.83333333 0.83333333]
-----------------
RandomForestClassifier() being used
train scores: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
test scores: [1.         0.33333333 0.16666667 0.33333333 0.5        0.5
 1.         0.5        0.66666667 0.33333333]
-----------------
DecisionTreeClassifier() being used
train scores: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
test scores: [0.5        0.33333333 0.66666667 0.5        0.66666667 0.5
 0.5        0.5        0.5        0.83333333]
-----------------
ExtraTreesClassifier() being used
train scores: [1. 1. 1.

# PLS

# LDA

# Random Projection

# Auto Encoder