# Imports

In [6]:
from sklearn import svm
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import KFold, cross_validate, LeaveOneOut, train_test_split, GridSearchCV
import pandas as pd

# Information on Support vector machines
[sklearn website](https://scikit-learn.org/stable/modules/svm.html#svm-kernels)

# Create some fake data

In [2]:
X = np.random.rand(20)
print(X)

[0.00308122 0.25865966 0.83600584 0.34755135 0.46534994 0.6492493
 0.16142487 0.52242716 0.66373048 0.0580653  0.65593346 0.84373899
 0.1540254  0.77479057 0.40662182 0.13985343 0.54261936 0.5815225
 0.57731462 0.74569474]


In [3]:
## reshape data for fitting model
X = X.reshape(-1,1)
print(X)

[[0.00308122]
 [0.25865966]
 [0.83600584]
 [0.34755135]
 [0.46534994]
 [0.6492493 ]
 [0.16142487]
 [0.52242716]
 [0.66373048]
 [0.0580653 ]
 [0.65593346]
 [0.84373899]
 [0.1540254 ]
 [0.77479057]
 [0.40662182]
 [0.13985343]
 [0.54261936]
 [0.5815225 ]
 [0.57731462]
 [0.74569474]]


In [4]:
y = np.random.randint(0,2, size=20)
print(y)

[0 1 1 0 0 0 1 1 1 1 0 1 0 1 0 1 0 1 1 0]


# Call our SVM module to create an instance of a classifier

In [5]:
clf = svm.SVC()

## Explore the inputs of the SVC

In [6]:
svm.SVC??

Init signature:
svm.SVC(
    *,
    C=1.0,
    kernel='rbf',
    degree=3,
    gamma='scale',
    coef0=0.0,
    shrinking=True,
    probability=False,
    tol=0.001,
    cache_size=200,
    class_weight=None,
    verbose=False,
    max_iter=-1,
    decision_function_shape='ovr',
    break_ties=False,
    random_state=None,
)
Source:        
class SVC(BaseSVC):
    """C-Support Vector Classification.

    The implementation is based on libsvm. The fit time scales at least
    quadratically with the number of samples and may be impractical
    beyond tens of thousands of samples. For large datasets
    consider using :class:`~sklearn.svm.LinearSVC` or
    :class:`~sklearn.linear_model.SGDClassifier` instead, possibly after a
    :class:`~sklearn.kernel_approximation.Nystroem` transformer.

    The multiclass support is handled according to a one-vs-one scheme.

    For details on the precise mathematical formulation of the provided
    kernel functions and how `gamma`, `coef0` and `degr

# Fit model

In [11]:
# Fit the model to x and y
clf.fit(X,y)

SVC()

In [12]:
# Verify we only have two classes
clf.classes_

array([0, 1])

## See how well the training data fits

In [13]:
# Get the training classification score
clf.score(X,y)

0.6

# What if we change the kernel?

In [14]:
# Kernels accepted by the function
list_kerns = ['linear', 'poly', 'rbf', 'sigmoid']

# Loop over them and train a model

for kernel in list_kerns:
    print(f'Kernel being used is {kernel}')
    clf = svm.SVC(kernel=kernel)
    clf.fit(X,y)
    print(clf.score(X,y))


Kernel being used is linear
0.55
Kernel being used is poly
0.55
Kernel being used is rbf
0.6
Kernel being used is sigmoid
0.55


# Grid Search

In [7]:
data_df = pd.read_csv('./data/60x61.csv', header=None)
data_df.head()

0         1         2         3         4         5         6         7   \
0   1  0.062832  0.097064  0.041652  0.008974  0.093586  0.011168  0.010246   
1   1  0.025996  0.056383  0.052404  0.079622  0.070710  0.046787  0.004721   
2   1  0.015806  0.099749  0.082649  0.076439  0.045748  0.061168  0.037715   
3   1  0.096576  0.021273  0.071937  0.023003  0.051179  0.026095  0.014747   
4   1  0.024500  0.038100  0.019063  0.004089  0.023010  0.104540  0.075521   

         8         9   ...        51        52        53        54        55  \
0  0.097714  0.093843  ...  0.003632  0.028356  0.066206  0.062532  0.100370   
1  0.034333  0.059902  ...  0.068505  0.030921  0.004277  0.059342  0.059611   
2  0.105080  0.111370  ...  0.073260  0.008919  0.012060  0.038680  0.013767   
3  0.027601  0.011309  ...  0.075601  0.028319  0.004177  0.026253  0.025739   
4  0.032552  0.018125  ...  0.061589  0.030194  0.004605  0.041527  0.050398   

         56        57        58        59        60  
0  0.069072  0.025882  0.054651  0.112760  0.106070  
1  0.025914  0.018308  0.102880  0.078364  0.049836  
2  0.014770  0.028393  0.088890  0.021125  0.014470  
3  0.018103  0.075973  0.057072  0.043127  0.024063  
4  0.008049  0.125900  0.101010  0.026404  0.004397  

[5 rows x 61 columns]

In [8]:
y = data_df.iloc[:,0]
X = abs(data_df.iloc[:,1:])

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, train_size=0.8)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)

(48, 60)
(12, 60)
(48,)


In [9]:
params = {
    'C': [1,10,100,1000],
    'gamma': ['scale','auto',0.01, 0.001, 0.0001]
}

In [10]:
# get cv
loo = LeaveOneOut()

# initalize model
svm_clf = svm.SVC(kernel='rbf')
grid = GridSearchCV(svm_clf, cv=loo, param_grid=params)

In [11]:
# fit the model
grid.fit(X,y)

GridSearchCV(cv=LeaveOneOut(), estimator=SVC(),
             param_grid={'C': [1, 10, 100, 1000],
                         'gamma': ['scale', 'auto', 0.01, 0.001, 0.0001]})

In [15]:
pd.DataFrame(grid.cv_results_).sort_values('mean_test_score', ascending=False)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
17       0.000760      0.000029         0.000484        0.000014    1000   
16       0.000804      0.000038         0.000485        0.000016    1000   
0        0.000903      0.000232         0.000568        0.000098       1   
5        0.000766      0.000019         0.000487        0.000016      10   
15       0.000763      0.000028         0.000481        0.000013    1000   
10       0.000761      0.000029         0.000484        0.000016     100   
11       0.000721      0.000027         0.000483        0.000020     100   
6        0.000729      0.000030         0.000492        0.000023      10   
7        0.000727      0.000029         0.000489        0.000023      10   
8        0.000727      0.000034         0.000486        0.000018      10   
9        0.000716      0.000023         0.000483        0.000019      10   
1        0.000734      0.000023         0.000491        0.000014       1   
12       0.000723      0.000030         0.000487        0.000027     100   
13       0.000719      0.000024         0.000480        0.000013     100   
14       0.000712      0.000021         0.000482        0.000034     100   
4        0.000725      0.000033         0.000486        0.000013       1   
3        0.000730      0.000026         0.000490        0.000016       1   
2        0.000744      0.000035         0.000497        0.000021       1   
18       0.000713      0.000021         0.000480        0.000018    1000   
19       0.000719      0.000032         0.000485        0.000020    1000   

   param_gamma                         params  split0_test_score  \
17        0.01     {'C': 1000, 'gamma': 0.01}                1.0   
16        auto   {'C': 1000, 'gamma': 'auto'}                1.0   
0        scale     {'C': 1, 'gamma': 'scale'}                1.0   
5        scale    {'C': 10, 'gamma': 'scale'}                1.0   
15       scale  {'C': 1000, 'gamma': 'scale'}                1.0   
10       scale   {'C': 100, 'gamma': 'scale'}                1.0   
11        auto    {'C': 100, 'gamma': 'auto'}                1.0   
6         auto     {'C': 10, 'gamma': 'auto'}                1.0   
7         0.01       {'C': 10, 'gamma': 0.01}                1.0   
8        0.001      {'C': 10, 'gamma': 0.001}                1.0   
9       0.0001     {'C': 10, 'gamma': 0.0001}                1.0   
1         auto      {'C': 1, 'gamma': 'auto'}                1.0   
12        0.01      {'C': 100, 'gamma': 0.01}                1.0   
13       0.001     {'C': 100, 'gamma': 0.001}                1.0   
14      0.0001    {'C': 100, 'gamma': 0.0001}                1.0   
4       0.0001      {'C': 1, 'gamma': 0.0001}                1.0   
3        0.001       {'C': 1, 'gamma': 0.001}                1.0   
2         0.01        {'C': 1, 'gamma': 0.01}                1.0   
18       0.001    {'C': 1000, 'gamma': 0.001}                1.0   
19      0.0001   {'C': 1000, 'gamma': 0.0001}                1.0   

    split1_test_score  split2_test_score  ...  split53_test_score  \
17                1.0                1.0  ...                 1.0   
16                1.0                1.0  ...                 1.0   
0                 1.0                1.0  ...                 1.0   
5                 1.0                1.0  ...                 1.0   
15                1.0                1.0  ...                 1.0   
10                1.0                1.0  ...                 1.0   
11                1.0                1.0  ...                 0.0   
6                 1.0                1.0  ...                 0.0   
7                 1.0                1.0  ...                 0.0   
8                 1.0                1.0  ...                 0.0   
9                 1.0                1.0  ...                 0.0   
1                 1.0                1.0  ...                 0.0   
12                1.0                1.0  ...                 0.0   
13          

In [16]:
print(grid.best_estimator_)
print(grid.best_params_)
print(grid.best_index_)
print(grid.best_score_)

SVC(C=1000, gamma='auto')
{'C': 1000, 'gamma': 'auto'}
16
0.9833333333333333
